import Link from "next/link";
import { Providers } from "../providers";
import { IS_CONFIGURED } from "@/lib/turmoil";

/*
  Chrome for the working pages — collector, sign, receipt. The landing at / sits
  outside this group and brings its own navigation, because a marketing header
  and a field-tool header have different jobs.

  Colour classes here are `text-fail` / `border-line`, generated by the @theme
  block. Do NOT use the bare-CSS-variable arbitrary form that Tailwind v3.3
  allowed — v4 dropped it and compiles it to a declaration with a raw custom
  property name as its value, which is invalid CSS the browser silently
  discards. Writing an example of it even inside a comment is enough for the
  class scanner to emit the dead rule, so there isn't one here.
*/
export default function AppLayout({ children }: { children: React.ReactNode }) {
  return (
    <Providers>
      <div className="relative min-h-screen overflow-hidden">
        {/*
          Two dim droplets. Frosted glass over a flat void reads as grey plastic —
          backdrop-filter has nothing to refract. These give it something, at half
          the landing's intensity so the working pages stay calmer than the pitch.
        */}
        <div aria-hidden className="pointer-events-none absolute inset-0">
          <div className="drop glow absolute -top-32 right-0 h-[26rem] w-[26rem] bg-oil opacity-[0.09]" />
          <div className="drop glow absolute bottom-0 -left-32 h-[22rem] w-[22rem] bg-oil opacity-[0.06]" />
        </div>

        <div className="relative z-10">
          {/*
            An unset NEXT_PUBLIC_TURMOIL_ADDRESS binds the zero address into the
            EIP-712 domain, so every signature recovers to a stranger and attest()
            reverts — indistinguishable from forgery. Say so, rather than letting
            a misconfigured deploy look exactly like a broken one.
          */}
          {!IS_CONFIGURED && (
            <p className="label border-b border-fail bg-fail/10 px-5 py-3 text-fail">
              Not configured — NEXT_PUBLIC_TURMOIL_ADDRESS is unset. Signing is disabled;
              nothing on this page is reading a real contract.
            </p>
          )}

          <header className="glass-nav sticky top-0 z-20">
            <div className="mx-auto flex max-w-5xl items-baseline gap-6 px-5 py-4">
              <Link href="/" className="datum text-lg tracking-[0.28em] text-oil">
                TURMOIL
              </Link>
              <nav className="label flex gap-5">
                <Link href="/collect" className="transition-colors hover:text-paper">
                  Pickup
                </Link>
                <Link href="/lot/0" className="transition-colors hover:text-paper">
                  Provenance
                </Link>
              </nav>
            </div>
          </header>

          <main className="mx-auto max-w-5xl px-5 py-10">{children}</main>

          <footer className="mx-auto max-w-5xl px-5 pb-10">
            <p className="label leading-relaxed">
              Testnet. Every figure on this page is read from the contract, not stored by us.
            </p>
          </footer>
        </div>
      </div>
    </Providers>
  );
}
